# Generated by Django 5.2.11 on 2026-04-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('groupes_cibles', models.CharField(max_length=50)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.TimeField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagnes.campagne')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donneur')),
            ],
        ),
    ]
