# Generated by Django 5.2.11 on 2026-04-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantite', models.PositiveIntegerField(help_text='Nombre de poches')),
                ('delai', models.DateField(help_text='Date limite')),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('satisfaite', 'Satisfaite'), ('cloturee', 'Clôturée')], default='active', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hopital')),
            ],
        ),
    ]
